inherit_from: .rubocop_todo.yml
# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# This is a basic RuboCop configuration file
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**/*
    - draft/**/*

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance
